### ISSUE TITLE
` Error: The pages (generated) and (generated) have the same output path "/pagefind/pagefind.js"` when using the esbuild plugin

### ISSUE THREAD

**Issue by ooker777** [lumeland/theme-simple-wiki#20]
I init a new project and have this `_config.ts`:
```ts
import lume from "lume/mod.ts";
import wiki from "wiki/mod.ts";
import esbuild from "lume/plugins/esbuild.ts";

const site = lume();

site.use(wiki());
site.use(esbuild({
  extensions: [".ts", ".js"],
  options: {
    plugins: [],
    bundle: true,
    format: "esm",
    minify: true,
    keepNames: true,
    platform: "browser",
    target: "esnext",
    entryPoints: ["./scripts/run.ts"],
    treeShaking: true,
    outdir: "./",
    outbase: ".",
  },
}));

export default site;
```
The result:
```
error: Uncaught (in worker "") (in promise) Error: The pages (generated) and (generated) have the same output path "/pagefind/pagefind.js". Use distinct 'url' values to resolve the conflict.
        throw new Error(
              ^
    at FSWriter.savePage (https://deno.land/x/lume@v2.4.3/core/writer.ts:83:15)
    at eventLoopTick (ext:core/01_core.js:175:7)        
    at async https://deno.land/x/lume@v2.4.3/core/writer.ts:50:13
    at async Promise.all (index 22)
    at async concurrent (https://deno.land/x/lume@v2.4.3/core/utils/concurrent.ts:21:3)
    at async FSWriter.savePages (https://deno.land/x/lume@v2.4.3/core/writer.ts:47:5)
    at async Site.build (https://deno.land/x/lume@v2.4.3/core/site.ts:547:19)
    at async buildSite (https://deno.land/x/lume@v2.4.3/cli/utils.ts:48:3)
    at async build (https://deno.land/x/lume@v2.4.3/cli/build_worker.ts:38:16)
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:175:7)   
```
However, if I remove the wiki theme, then it works. I have no `components.ts`

**Comment by ooker777** [comment]
nevermind I need to place `site.use(wiki());` after `site.use(esbuild())`

**Comment by oscarotero** [comment]
@ooker777 
That's a bug. It should work with any other. I'll fix in the next Lume version. Thanks!
